config/routes.rb
IFMR1::Application.routes.draw do
  
  resources :settings

  get "admin/main"

  get "admin/sub1"

  get "admin/sub2"

  post "images/new"
  
  resources :images

  root to: "images#index"
  
  
  

end

app/models/image.rb
class Image < ActiveRecord::Base
end

app/controllers/images_controller.rb
$KCODE='u'

require_dependency 'basic'
include Basic

class ImagesController < ApplicationController
  
  # REF global http://doc.ruby-lang.org/ja/1.9.3/doc/spec=2fvariables.html#global
  $remote_url = "http://benfranklin.chips.jp/images"
  # $remote_url = "http://benfranklin.chips.jp/image_thumbnails"
  # $log_file_path = "doc/mylog.txt"
  $log_file_path = "doc/mylog/log.log"
  
  # GET /images
  # GET /images.json
  def index

        per_page = 10
        
        # Total number of images
        @total_num_of_images = Image.all.length
        
        @server_info = request.host_with_port
        
        # Params => Search
        @images = _index_1_search_text(per_page)
  
      @contentArray = _index_get_log()
  
  
      respond_to do |format|
          format.html # index.html.erb
          format.json { render json: @images }
      end
  end

    def _index_1_search_text(per_page)
        if params['search'] and params['search']['text']
        
            search_word = params['search']['text']

            # Logic option
            # # if params ['search']['option_logic']
            # if params ['search']['option_logic'] == "search_logic_all"
            if params['search']['option_logic']
                
                # if params ['search']['option_logic'] == "search_logic_all"
                if params['search']['option_logic'] == "search_logic_all"
                    
                    return Image.paginate(
                          :page => params[:page],
                          :order => 'created_at asc',
                          :per_page => per_page,
                          :conditions => ['memos LIKE ?', "%#{search_word}%"])

                elsif params['search']['option_logic'] == "search_logic_and"
                    
                    return _index_1_search_text_1_and(per_page)
                          
                elsif params['search']['option_logic'] == "search_logic_or"
                    
                    return _index_1_search_text_2_or(per_page)
                          
                else
                    
                    return Image.paginate(
                          :page => params[:page],
                          :order => 'created_at asc',
                          :per_page => per_page)                    
                          
                end#if params['search']['option_logic'] == "search_logic_all"
                
            end#if params ['search']['option_logic']
            
            return Image.paginate(
                          :page => params[:page],
                          :order => 'created_at asc',
                          :per_page => per_page,
                          :conditions => ['memos LIKE ?', "%#{search_word}%"])

        
        else
            
            return Image.paginate(
                                  :page => params[:page],
                                  :order => 'created_at asc',
                                  :per_page => per_page)
                                  
        end#if params['search'] and params['search']['text']
        
    end#def _index_1_search_text
    
    def _index_1_search_text_1_and(per_page)
        
        search_words = params['search']['text']
        
        a = search_words.split(" ")
        
        q = []
        
        condition = []
        
        a.length.times do
        
            q.push("memos like ?")
            
        end#a.length.times do
        
        q = q.join(" and ")
        
        condition.push(q)

        a.length.times do |i|
            
            token = "%#{a[i]}%"
            
            condition.push(token)
            
        end
        
        #logout("condition=" + condition.to_s, __FILE__, __LINE__)
        
        return Image.paginate(
                  :page => params[:page],
                  :order => 'created_at asc',
                  :per_page => per_page,
                  :conditions => condition)
                  
    end#_index_1_search_text_1_and(per_page)
    
    def _index_1_search_text_2_or(per_page)
        
        search_words = params['search']['text']
        
        a = search_words.split(" ")
        
        q = []
        
        condition = []
        
        a.length.times do
        
            q.push("memos like ?")
            
        end#a.length.times do
        
        q = q.join(" or ")
        
        condition.push(q)

        a.length.times do |i|
            
            token = "%#{a[i]}%"
            
            condition.push(token)
            
        end
        
        #logout("condition=" + condition.to_s, __FILE__, __LINE__)
        
        return Image.paginate(
                  :page => params[:page],
                  :order => 'created_at asc',
                  :per_page => per_page,
                  :conditions => condition)
                  
    end#_index_1_search_text_1_and(per_page)
    
  def _index_get_log()
      
      if File.exists?($log_file_path)
      
      # File.open(target, "r") do |f|
#         
        # @contentArray = f.each_line {|line|}
        # # @content = f.read()
        # # f.write(content)
        # # f.write("\n")
      # end

        # => http://www.ruby-forum.com/topic/66733
          # @contentArray = File.readlines(target)
          
          lines = File.readlines($log_file_path)
          
          if lines.length > 0
            
              return lines
              # return File.readlines(target)
            
          else
            
              return ["no data written"]
            
          end
  
      else
        
          return ["no data"]
          # @content = "abcdefg"
        
      end
    
  end#def _index_get_log()

  # GET /images/1
  # GET /images/1.json
  def show
    @image = Image.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @image }
    end
  end

  # GET /images/new
  # GET /images/new.json
  def new
      
      res = _new__1_data_from_device()
      
      logout("res=" + res.to_s, __FILE__, __LINE__)
      
      if res == true
          
          redirect_to :controller => 'images', :action => 'index'
          
          return
        
      end
      
      # #---------------------------------------------
      # # Post from  the device
      # #---------------------------------------------
      # dev_file_name = false
      # dev_table_name = false
#       
      # # File name ----------------------------------
      # if params['file_name']
#         
          # msg = "params['file_name'] => " + params['file_name']
#           
          # dev_file_name = true
#         
      # else
#       
          # msg = "params['file_name'] => null"
# 
      # end
# 
# #           
      # logout(msg, __FILE__, __LINE__)
      # # logout(msg)
#   
      # # Table name -------------------------------------
      # if params['table_name']
#         
          # msg = "params['table_name'] => " + params['table_name']
#           
          # dev_table_name = true
#         
      # else
#       
          # msg = "params['table_name'] => null"
# 
      # end      
#       
      # logout(msg, __FILE__, __LINE__)
      # # logout(msg)
#       
      # # Save image
      # if dev_file_name
#           
          # msg = "dev_file_name => true"
          # logout(msg, __FILE__, __LINE__)
# 
#           
          # image = Image.new()
#           
          # image.file_name = params['file_name']
          # image.table_name = params['table_name']
#           
#           
#           
          # respond_to do |format|
              # if image.save
#                   
                  # msg = "image.save => Done"
                  # logout(msg, __FILE__, __LINE__)
#                 
                  # format.json { render json: image}
                  # # format.json { render json: image, status: :created, location: image }
#                   
              # else
# 
                # msg = "image.save => Failed"
                # logout(msg, __FILE__, __LINE__)
#                 
                # format.json { render json: image}
                # # format.json { render json: image.errors, status: :unprocessable_entity }
#                 
              # end
#               
              # return
          # end#respond_to do |format|
#           
      # else#if dev_file_name
#         
      # end#if dev_file_name
      
      
            
      @image = Image.new
  
      respond_to do |format|
          format.html # new.html.erb
          format.json { render json: @image }
      end
  end


  # GET /images/1/edit
  def edit
    @image = Image.find(params[:id])
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(params[:image])

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render json: @image, status: :created, location: @image }
      else
        format.html { render action: "new" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /images/1
  # PUT /images/1.json
  def update
    @image = Image.find(params[:id])

    respond_to do |format|
      if @image.update_attributes(params[:image])
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image = Image.find(params[:id])
    @image.destroy

    respond_to do |format|
      format.html { redirect_to images_url }
      format.json { head :no_content }
    end
  end
  
private
  #===================================

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :file_name %><br />
    <%= f.text_field :file_name %>
  </div>
  <div class="field">
    <%= f.label :file_path %><br />
    <%= f.text_field :file_path %>
  </div>
  <div class="field">
    <%= f.label :memos %><br />
    <%= f.text_area :memos %>
  </div>
  <div class="field">
    <%= f.label :tags %><br />
    <%= f.text_field :tags %>
  </div>
  <div class="field">
    <%= f.label :table_name %><br />
    <%= f.text_field :table_name %>
  </div>
  <div class="field">
    <%= f.label :last_viewed_at %><br />
    <%= f.number_field :last_viewed_at %>
  </div>
  <div class="field">
    <%= f.label :created_at_mill %><br />
    <%= f.number_field :created_at_mill %>
  </div>
  <div class="field">
    <%= f.label :updated_at_mill %><br />
    <%= f.number_field :updated_at_mill %>
  </div>
  <div class="field">
    <%= f.label :date_added %><br />
    <%= f.number_field :date_added %>
  </div>
  <div class="field">
    <%= f.label :date_modified %><br />
    <%= f.number_field :date_modified %>
  </div>
  <div class="field">
    <%= f.label :loc_file_id %><br />
    <%= f.number_field :loc_file_id %>
  </div>
  <div class="field">
    <%= f.label :loc_created_at %><br />
    <%= f.number_field :loc_created_at %>
  </div>
  <div class="field">
    <%= f.label :loc_modified_at %><br />
    <%= f.number_field :loc_modified_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/_index_logs.html.erb
<!-- REF display http://stackoverflow.com/questions/4474327/how-to-make-a-div-hidden-by-default-made-by-a-content-tag-for -->
<a href="#bottom" style="margin: 0px 25px;" class="link">(To bottom)</a>
<div id="logs" style="display: none;">

	<% for i in 0..@contentArray.length - 1 %>
	
		<%= @contentArray[i] %><br />
	
	<% end %>
	
	<input type="button" value="Hide log"   class="hide_button" disabled/>
	
</div>

app/views/images/_index_table_entries.html.erb
<% i = 1 %>

<% @images.each do |image| %>
	<% if i % 4 == 0 %>
		
		<tr>
			<td colspan="5">
				<a href="#top" style="margin: 0px 25px;", class="link">(To top)</a> | 
				<a href="#bottom" style="margin: 0px 25px;" class="link">(To bottom)</a>
			</td>
		</tr>
		
	<% end %>
	
  <tr>
    <td><%= image.id %></td>
    <td colspan="2" style="background: Khaki; color: Black;">
    	<%= link_to image.file_name, image %>
    </td>

    <td colspan="2"><%= image.table_name %></td>
   </tr>
   
   <tr>
    <td colspan="4">
    	<!-- REF using class: http://stackoverflow.com/questions/10185516/how-to-style-an-image-tag-in-ruby-on-rails answered Apr 17 '12 at 5:22 -->
    	<% if image.file_name != nil %>
	    	<%= link_to\
	    			image_tag(
	    				$remote_url + '/' + image.file_name,
	    				{:alt => $remote_url + '/' + image.file_name,
	    					:class => "index_image_tag"}),
	    			image %>
	    <% else %>
	    
	    	No data: <%= image.class.to_s %>
	    
	    
	    <% end %>
	    
    </td>
    
    
    <td><%= image.file_path %>
    
    <%= image.memos %>
    <hr />
        
    <%= image.tags %>
    <hr />
    
    <%= image.loc_file_id %>
    <hr />

    <%= link_to 'Destroy', image, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
  
  <% i = i + 1 %>
  
<% end %>

app/views/images/_index_table_header.html.erb
<!--   <tr>
    <th>Id</th>
    <th class="index_header_thumbnail">Thumbnail</th>
    <th>File name</th>
    <th>File path</th>
    <th>Memos</th>
    <th>Tags</th>
    <th>Table name</th>
    <th>Loc file</th>

    <th></th>
  </tr>
-->

app/views/images/_index_tool_bar.html.erb
<!-- REF float http://www.htmq.com/style/float.shtml -->
<div style="float: left;">
	<!-- http://railsdoc.com/references/form_for -->
	<%#= form_tag('/images/index') do %>
	<%= form_tag('/images', {:method => "get"}) do %>
	
		Search word (in 'Memo' column):
			<%= text_field\
						:search,
						:text,
						{:size => 20, :style => "background: Aquamarine"} %>
		
		<!-- Radio buttons -->
		<!-- REF http://railsdoc.com/form#%E3%83%A9%E3%82%B8%E3%82%AA%E3%83%9C%E3%83%83%E3%82%AF%E3%82%B9(radio_button) -->
		<%= radio_button\
				'search',
				"option_logic",
				'search_logic_all',
				:id => "search_logic_all",
				:checked => true %>
				
		<!-- REF label http://d.hatena.ne.jp/kaorumori/20101028/1289874655 -->
		<%= label 'search_logic_all', "All" %>
		
		<%= radio_button\
				'search',
				"option_logic",
				'search_logic_and',
				:id => "search_logic_and"
				%>
		<%= label 'search_logic_and', "And" %>
				
		<%= radio_button\
				'search',
				"option_logic",
				'search_logic_or',
				:id => "search_logic_or"
				%>
		<%= label 'search_logic_or', "Or" %>
				
		<%= submit_tag "Go" %>
	
	<% end %>
	
</div>

<%= form_tag('/images', {:method => "get"}) do %>

	
	
	<%= submit_tag "Clear conditions" %>

<% end %>

<!-- REF http://stackoverflow.com/questions/7712030/how-to-create-a-box-that-hovers-above-existing-text answered Oct 10 '11 at 11:43 -->
<style type="text/css">
	.container ul {
	display: none;       
	}
	.container:hover ul{
	display: inline;  /* or block or whatever you need */
	}
</style>

<!-- 
<div class="container">
	<p>Sort By</p>
	
	<ul>
	    <li>title</li>
	    <li>date</li>
	    <li>artist</li>
	</ul>
</div>
-->

<div>
	<a href="https://twitter.com/intent/tweet?screen_name=TwitterHelpJP" class="twitter-mention-button" data-lang="ja" data-size="large" data-related="www">Tweet to @TwitterHelpJP</a>
	<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
</div>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<a name="top"></a>

<h1>Listing images (Total=<%= @total_num_of_images %>)</h1>

ABC

<script type="text/javascript">


	// REF function http://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_document_getelementbyid
	function rotate_image2(deg) {
		
		// alert("rotate");
		var angle = 0, img = document.getElementById('container');
		
		angle = (angle+deg)%360;
		//angle = (angle+90)%360;
		
		img.className = "rotate"+angle;
		
		
	}
	function rotate_image() {
		
		// alert("rotate");
		var angle = 0, img = document.getElementById('container');
		
		angle = (angle+90)%360;
		
		img.className = "rotate"+angle;
		
		
	}
	// var angle = 0, img = document.getElementById('container');
// 	
	// // alert("container");
// 	
	// document.getElementById('button').onclick = function() {
// 		
		// alert("button");
	    // // angle = (angle+90)%360;
	    // // img.className = "rotate"+angle;
	// }
</script>

<button id="button" onclick="rotate_image2(90);">Click +90!</button>
<button id="button" onclick="rotate_image2(-90);">Click -90!</button>
<button id="button" onclick="rotate_image2(-180);">Click -180!</button>
<button id="button" onclick="rotate_image2(-270);">Click -270!</button>
<button id="button" onclick="rotate_image2(+180);">Click +180!</button>
<button id="button" onclick="rotate_image2(+270);">Click +270!</button>
<button id="button" onclick="rotate_image();">Click me!</button>
<!-- <button id="button">Click me!</button> -->

<div id="container">
	<img
		src="http://benfranklin.chips.jp/images/2012-04-14_08-07-07_188.jpg"
		id="image"
		 width="300" height="300"/>
</div>
Rotate image
<hr />


<a href="#bottom" style="margin: 0px 25px;" class="link">(To bottom)</a>

<hr />
	
	<%= render :partial => "index_tool_bar" %>
	
<hr />

	<%= will_paginate @images, :prev_label=>'«Previous', :next_label=>'Next»' %>
	
<hr />

<table>

	<%= render :partial => "index_table_header" %>
	
	<%= render :partial => "index_table_entries" %>
		
</table>

<hr />
	<%= will_paginate @images, :prev_label=>'«Previous', :next_label=>'Next»' %>
<hr />


<br />

<%= link_to 'New Image', new_image_path %>

<hr />

<% if @server_info.start_with?("localhost") %>

	<%= link_to "Heroku site", "http://cosmos-ifm-1.herokuapp.com/", :target => "_blank" %> |
	
<% else %>

	<%= link_to "Local site", "http://localhost:3001/", :target => "_blank" %>
	
<% end %>

<hr />
<input type="button" value="Show log"   id="show_button" /> |
<!--
	REF disabled http://html.eweb-design.com/0903_btn.html
-->
<input type="button" value="Hide log"   class="hide_button" disabled/>

<p>CLICK here</p>

<!-- <div id="logs"> -->

<%= render :partial => "index_logs" %>

<a href="#top" style="margin: 0px 25px;", class="link">(To top)</a>
<a name="bottom"></a>

app/views/images/new.html.erb
<h1>New image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

<br />

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<div>
	<%= @image.file_name %> (<a href="#file_info">File info</a>)
</div>

<hr />

<button class="button" id="rotate_back" onclick="rotate_image2(-90);">Back</button>
<button class="button" onclick="rotate_image2(90);">+90 right</button>
<button class="button" onclick="rotate_image2(270);">-90 right</button>
<button class="button" onclick="rotate_image2(180);">Upside down</button>

<div id="container">
	<!-- <img src="<%#= $remote_url + '/' + @image.file_name %>" style="width: 50%; height: 50%" /> -->
	<img src="<%= $remote_url + '/' + @image.file_name %>" id="image" />
	<!-- <img src="<%#= $remote_url + '/' + @image.file_name %>" /> -->
</div>

<br />
<hr />

<div id="file_info">
	
	
	<table>
		
		<tr>
			<td>
				<b>File name</b>
			</td>
			<td>
				<%= @image.file_name %>
			</td>
		</tr>
		
		<tr>
			<td>
				File path
			</td>
			<td>
				<%= @image.file_path %>
			</td>
		</tr>
		
		<tr>
			<td>
				<b>Memos</b>
			</td>
			<td>
				<%= @image.memos %>
			</td>
		</tr>
		
		<tr>
			<td>
				<b>Tags</b>
			</td>
			<td>
				<%= @image.tags %>
			</td>
		</tr>
		
		<tr>
			<td>
				<b>Table name</b>
			</td>
			<td>
				<%= @image.table_name %>
			</td>
		</tr>
		
		<tr>
			<td>
				<b>Loc file</b>
			</td>
			<td>
				<%= @image.loc_file_id %>
			</td>
		</tr>
		
	</table>
</div>

<div>
	<a href="#top">Top</a>
</div>

<br />
<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>